version: 0.0
os: linux
files:
  - source: /app/
    destination: /home/ubuntu
permissions:
  - object: /home/ubuntu/
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: afterInstall.sh
      timeout: 10
      runas: ubuntu
