name: Upload to S3

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때만 실행

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    # 1. 리포지토리 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. AWS CLI 설치
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    # 3. AWS 환경 변수 설정
    - name: Configure AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region ap-northeast-2  # 필요한 경우 다른 지역 설정

    # 4. S3에 파일 업로드
    - name: Upload file to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp ./* s3://codepipeline-ap-northeast-2-334239444201/prj1
